// Mock data for demo mode (when Supabase is not configured)

export const mockUsers = [
  {
    id: 'demo-user-1',
    email: 'demo@umit.asia',
    first_name: 'Демо',
    last_name: 'Пользователь',
    role: 'volunteer',
    phone: '+7 777 123 4567',
    avatar: null,
    rating: 4.8,
    verified: true,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'demo-user-2',
    email: 'beneficiary@example.com',
    first_name: 'Нуржан',
    last_name: 'Алматов',
    role: 'beneficiary',
    verified: true,
    created_at: '2024-01-15T00:00:00Z',
  },
  {
    id: 'demo-donor-1',
    email: 'donor@example.com',
    first_name: 'Айгуль',
    last_name: 'Каримова',
    role: 'donor',
    phone: '+7 777 555 6677',
    verified: true,
    rating: 4.9,
    created_at: '2024-02-01T00:00:00Z',
  },
]

export const mockLocations = [
  {
    id: 'location-1',
    address: 'ул. Абая 150',
    city: 'Алматы',
    region: 'Алматинская область',
    country: 'Казахстан',
    latitude: 43.238293,
    longitude: 76.889709,
  },
  {
    id: 'location-2',
    address: 'пр. Республики 15',
    city: 'Астана',
    region: 'Акмолинская область',
    country: 'Казахстан',
    latitude: 51.169392,
    longitude: 71.449074,
  },
  {
    id: 'location-3',
    address: 'ул. Санкибай батыра 25',
    city: 'Актобе',
    region: 'Актюбинская область',
    country: 'Казахстан',
    latitude: 50.283917,
    longitude: 57.167011,
  },
]

export const mockHelpRequests = [
  {
    id: 'request-1',
    title: 'Нужна помощь с продуктами',
    description: 'Семья из 4 человек, требуется помощь с продуктами питания на месяц',
    category: 'food',
    status: 'pending',
    priority: 'high',
    beneficiary_id: 'demo-user-2',
    beneficiary: mockUsers[1],
    location_id: 'location-1',
    location: mockLocations[0],
    images: [],
    created_at: '2024-10-20T10:00:00Z',
    updated_at: '2024-10-20T10:00:00Z',
  },
  {
    id: 'request-2',
    title: 'Требуется зимняя одежда',
    description: 'Нужна теплая одежда для детей 5 и 8 лет',
    category: 'clothing',
    status: 'approved',
    priority: 'medium',
    beneficiary_id: 'demo-user-2',
    beneficiary: mockUsers[1],
    location_id: 'location-2',
    location: mockLocations[1],
    images: [],
    created_at: '2024-10-18T14:30:00Z',
    updated_at: '2024-10-19T09:00:00Z',
  },
]

export const mockShelters = [
  {
    id: 'shelter-1',
    name: 'Приют "Надежда"',
    description: 'Приют для животных. Принимаем корм, медикаменты, игрушки.',
    type: 'animal',
    location_id: 'location-1',
    location: mockLocations[0],
    contact_email: 'hope@shelter.kz',
    contact_phone: '+7 777 111 2233',
    images: [],
    verified: true,
    rating: 4.9,
    manager_id: 'demo-user-1',
    manager: mockUsers[0],
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'shelter-2',
    name: 'Социальный приют "Забота"',
    description: 'Социальный приют для людей в трудной жизненной ситуации',
    type: 'human',
    location_id: 'location-2',
    location: mockLocations[1],
    contact_email: 'care@shelter.kz',
    contact_phone: '+7 777 222 3344',
    images: [],
    verified: true,
    rating: 4.7,
    manager_id: 'demo-user-1',
    manager: mockUsers[0],
    created_at: '2024-02-01T00:00:00Z',
  },
]

export const mockVolunteers = [
  {
    id: 'volunteer-1',
    email: 'volunteer1@example.com',
    first_name: 'Айгуль',
    last_name: 'Сериковна',
    role: 'volunteer',
    rating: 4.9,
    verified: true,
    stats: {
      requests_completed: 45,
      volunteer_hours: 120,
      donations_made: 30,
    },
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'volunteer-2',
    email: 'volunteer2@example.com',
    first_name: 'Данияр',
    last_name: 'Бекович',
    role: 'volunteer',
    rating: 4.7,
    verified: true,
    stats: {
      requests_completed: 32,
      volunteer_hours: 85,
      donations_made: 25,
    },
    created_at: '2024-02-01T00:00:00Z',
  },
  {
    id: 'volunteer-3',
    email: 'volunteer3@example.com',
    first_name: 'Мадина',
    last_name: 'Токаева',
    role: 'volunteer',
    rating: 4.6,
    verified: true,
    stats: {
      requests_completed: 28,
      volunteer_hours: 70,
      donations_made: 20,
    },
    created_at: '2024-03-01T00:00:00Z',
  },
]

export const mockDonorOffers = [
  {
    id: 'offer-1',
    title: 'Детская одежда на 3-5 лет',
    description: 'Отдаю детскую одежду в отличном состоянии. Куртки, штаны, кофты. Всего около 15 вещей.',
    category: 'clothing',
    type: 'goods',
    status: 'active',
    donor_id: 'demo-donor-1',
    donor: mockUsers[2],
    location_id: 'location-1',
    location: mockLocations[0],
    quantity: 15,
    unit: 'шт',
    contact_phone: '+7 777 555 6677',
    contact_email: 'donor@example.com',
    created_at: '2024-10-25T10:00:00Z',
    updated_at: '2024-10-25T10:00:00Z',
    expires_at: '2024-11-25T23:59:59Z',
  },
  {
    id: 'offer-2',
    title: 'Бесплатная юридическая консультация',
    description: 'Предлагаю бесплатные юридические консультации по жилищным вопросам. Опыт работы 10 лет.',
    category: 'legal_service',
    type: 'service',
    status: 'active',
    donor_id: 'demo-donor-1',
    donor: mockUsers[2],
    location_id: 'location-2',
    location: mockLocations[1],
    contact_phone: '+7 777 555 6677',
    contact_email: 'donor@example.com',
    created_at: '2024-10-24T14:00:00Z',
    updated_at: '2024-10-24T14:00:00Z',
    expires_at: '2024-12-31T23:59:59Z',
  },
  {
    id: 'offer-3',
    title: 'Продукты питания (крупы, консервы)',
    description: 'Есть излишки продуктов: гречка 5кг, рис 3кг, консервы 10 банок. Срок годности в порядке.',
    category: 'food',
    type: 'goods',
    status: 'active',
    donor_id: 'demo-donor-1',
    donor: mockUsers[2],
    location_id: 'location-3',
    location: mockLocations[2],
    quantity: 18,
    unit: 'кг/шт',
    contact_phone: '+7 777 555 6677',
    created_at: '2024-10-26T09:00:00Z',
    updated_at: '2024-10-26T09:00:00Z',
    expires_at: '2024-11-10T23:59:59Z',
  },
  {
    id: 'offer-4',
    title: 'Репетиторство по математике',
    description: 'Помогу школьникам 5-9 классов с математикой. Онлайн или офлайн.',
    category: 'psychological_service',
    type: 'service',
    status: 'reserved',
    donor_id: 'demo-donor-1',
    donor: mockUsers[2],
    location_id: 'location-2',
    location: mockLocations[1],
    contact_email: 'donor@example.com',
    created_at: '2024-10-20T11:00:00Z',
    updated_at: '2024-10-23T15:00:00Z',
  },
  {
    id: 'offer-5',
    title: 'Холодильник в рабочем состоянии',
    description: 'Отдаю холодильник Indesit, работает хорошо. Просто купили новый. Самовывоз.',
    category: 'household',
    type: 'goods',
    status: 'active',
    donor_id: 'demo-donor-1',
    donor: mockUsers[2],
    location_id: 'location-1',
    location: mockLocations[0],
    quantity: 1,
    unit: 'шт',
    contact_phone: '+7 777 555 6677',
    created_at: '2024-10-27T08:00:00Z',
    updated_at: '2024-10-27T08:00:00Z',
    expires_at: '2024-11-15T23:59:59Z',
  },
  {
    id: 'offer-6',
    title: 'Бесплатная стрижка для пожилых людей',
    description: 'Парикмахер с 15-летним стажем. Приезжаю на дом к пожилым людям для стрижки. Бесплатно.',
    category: 'medical_service',
    type: 'service',
    status: 'active',
    donor_id: 'demo-donor-1',
    donor: mockUsers[2],
    location_id: 'location-3',
    location: mockLocations[2],
    contact_phone: '+7 777 555 6677',
    created_at: '2024-10-26T16:00:00Z',
    updated_at: '2024-10-26T16:00:00Z',
    expires_at: '2024-12-31T23:59:59Z',
  },
  {
    id: 'offer-7',
    title: 'Детские книги и учебники',
    description: 'Отдаю детские книги для возраста 7-12 лет, учебники за 1-4 классы. Около 30 книг.',
    category: 'clothing',
    type: 'goods',
    status: 'active',
    donor_id: 'demo-donor-1',
    donor: mockUsers[2],
    location_id: 'location-1',
    location: mockLocations[0],
    quantity: 30,
    unit: 'шт',
    contact_phone: '+7 777 555 6677',
    contact_email: 'donor@example.com',
    created_at: '2024-10-25T12:00:00Z',
    updated_at: '2024-10-25T12:00:00Z',
    expires_at: '2024-11-30T23:59:59Z',
  },
  {
    id: 'offer-8',
    title: 'Помощь в перевозке вещей',
    description: 'Есть грузовая Газель. Могу помочь с перевозкой мебели, вещей для нуждающихся. Бензин за свой счёт.',
    category: 'transport',
    type: 'service',
    status: 'active',
    donor_id: 'demo-donor-1',
    donor: mockUsers[2],
    location_id: 'location-2',
    location: mockLocations[1],
    contact_phone: '+7 777 555 6677',
    created_at: '2024-10-24T10:00:00Z',
    updated_at: '2024-10-24T10:00:00Z',
    expires_at: '2024-11-20T23:59:59Z',
  },
  {
    id: 'offer-9',
    title: 'Зимняя обувь женская 37-38 размер',
    description: 'Отдаю зимние сапоги и ботинки в хорошем состоянии. 3 пары.',
    category: 'clothing',
    type: 'goods',
    status: 'completed',
    donor_id: 'demo-donor-1',
    donor: mockUsers[2],
    location_id: 'location-3',
    location: mockLocations[2],
    quantity: 3,
    unit: 'пары',
    contact_phone: '+7 777 555 6677',
    created_at: '2024-10-15T14:00:00Z',
    updated_at: '2024-10-22T09:00:00Z',
    expires_at: '2024-10-30T23:59:59Z',
  },
  {
    id: 'offer-10',
    title: 'Компьютерная помощь',
    description: 'Помогу настроить компьютер, установить программы, решить проблемы. Для пожилых людей бесплатно.',
    category: 'medical_service',
    type: 'service',
    status: 'active',
    donor_id: 'demo-donor-1',
    donor: mockUsers[2],
    location_id: 'location-2',
    location: mockLocations[1],
    contact_phone: '+7 777 555 6677',
    contact_email: 'donor@example.com',
    created_at: '2024-10-23T11:00:00Z',
    updated_at: '2024-10-23T11:00:00Z',
    expires_at: '2024-12-31T23:59:59Z',
  },
  {
    id: 'offer-11',
    title: 'Корм для собак 20кг',
    description: 'Остался корм для собак крупных пород. Срок годности до марта 2025.',
    category: 'animal_care',
    type: 'goods',
    status: 'active',
    donor_id: 'demo-donor-1',
    donor: mockUsers[2],
    location_id: 'location-1',
    location: mockLocations[0],
    quantity: 20,
    unit: 'кг',
    contact_phone: '+7 777 555 6677',
    created_at: '2024-10-27T07:00:00Z',
    updated_at: '2024-10-27T07:00:00Z',
    expires_at: '2024-11-15T23:59:59Z',
  },
  {
    id: 'offer-12',
    title: 'Медикаменты (витамины, жаропонижающие)',
    description: 'Отдаю нераспечатанные лекарства: витамины, парацетамол, аспирин. Срок годности нормальный.',
    category: 'medicine',
    type: 'goods',
    status: 'active',
    donor_id: 'demo-donor-1',
    donor: mockUsers[2],
    location_id: 'location-3',
    location: mockLocations[2],
    quantity: 12,
    unit: 'упак',
    contact_phone: '+7 777 555 6677',
    created_at: '2024-10-26T13:00:00Z',
    updated_at: '2024-10-26T13:00:00Z',
    expires_at: '2024-11-10T23:59:59Z',
  },
]

// Mock auth state
let mockAuthUser: typeof mockUsers[0] | null = null

export const getMockAuthUser = () => mockAuthUser

export const setMockAuthUser = (user: typeof mockUsers[0] | null) => {
  mockAuthUser = user
}
